# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '15.0'

target 'ios-ba-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-ba-demo
  pod 'LibTorch-Lite'

end
